### ISSUE TITLE
left, top and width

### ISSUE THREAD

**Issue by olegosipenko87** [lukevink/hass-config-lajv#10]
Tell me please
how did you calculate these values ​​so accurately?

**left, top and width**

```
        - action: none
          entity: binary_sensor.bathroom
          image: /local/ui/floorplan/lights/bathroom.png
          state_filter:
            'off': opacity(0%)
            'on': opacity(100%)
            unknown: opacity(0%)
          style:
            left: 76.85%
            top: 78.2%
            width: 46.1328125%
            mix-blend-mode: lighten
          tap_action:
            action: none
          type: image
```
