### ISSUE TITLE
Button-card template 'color_light' is missing!

### ISSUE THREAD

**Issue by merccooper** [lukevink/hass-config-lajv#19]
Hi lukevink, amazing work! I've tried to recreate some parts from your config, however it seems that the color_light template in button_card_templates.yaml is missing, could you please update it, or point where this template is located.

Thank you very much

**Comment by stnokott** [comment]
I would also much appreciate adding that back!

**Comment by CR4567** [comment]
I think you can add this
```
  color_light:
    styles:
      card:
        - border-radius: 50%
        - height: 4em
        - width: 4em
        - margin: 4px
```

from the original has_config. 
Just add it to your button_card_templates.yaml.
