### ISSUE TITLE
All Devices : Cannot add property useTemperature, object is not extensible

### ISSUE THREAD

**Issue by JangoBritt** [lukevink/hass-config-lajv#2]
Hey Luke, I really love your dashboards... and I'm trying to duplicate using your code.

Obviously, I wanted to start by slotting in my devices, and then customising once I have everything working well.

On the All Devices pages (lovelace/1) I get a big red error screen 

```
Cannot add property useTemperature, object is not extensible
enableColumns: true
popup:
  brightnessHeight: 350px
  brightnessWidth: 130px
  scenesInARow: 2
  switchHeight: 300px
  switchWidth: 110px
  type: 'custom:light-popup-card'
rows:
  - columns:
      - column: 1
        entities:
          - entities:
              - entity: light.olivia_light
                icon: 'mdi:ceiling-light'
              - entity: light.dollhouse
              - entity: light.olivia_lamp
                icon: 'mdi:lamp'
            title: Olivia
        tileOnRow: 2
      - column: 3
        entities:
          - entities:
              - entity: light.bedroom_light_1
                icon: 'mdi:desk-lamp'
              - entity: light.bedroom_light_1
                icon: 'mdi:ceiling-light'
            title: Bedroom
        tileOnRow: 1
      - column: 3
        entities:
          - entities:
              - entity: light.office_light_1
                icon: 'mdi:ceiling-light'
              - entity: light.office_lamp
                icon: 'mdi:coach-lamp'
            title: Office
        tileOnRow: 1
      - column: 4
        entities:
          - entities:
              - entity: light.downstairs_hallway_light
                icon: 'mdi:track-light'
            title: Downstairs Hallway
        tileOnRow: 1
    row: 1
  - columns:
      - column: 1
        entities:
          - entities:
              - entity: light.kitchen_phoenix_1
              - entity: light.kitchen_phoenix_2
              - entity: light.kitchen_phoenix_3
              - entity: light.kitchen_phoenix_4
            title: Kitchen
        tileOnRow: 2
      - column: 2
        entities:
          - entities:
              - entity: light.back_door
                icon: 'mdi:lava-lamp'
              - entity: light.french_doors_1
                icon: 'mdi:lava-lamp'
            title: Roof
        tileOnRow: 1
      - column: 3
        entities:
          - entities:
              - entity: binary_sensor.downstairs_hallway_sensor_motion
                icon: 'mdi:walk'
            title: Motion
        tileOnRow: 1
      - column: 4
        entities:
          - entities:
              - entity: group.all_lights
                icon: 'mdi:home'
            title: All Lights
        tileOnRow: 1
    row: 2
statePositionTop: true
style:
  height: 87%
  left: 62%
  top: 50%
  width: 68%
type: 'custom:homekit-card'
```
