### ISSUE TITLE
"Flicker" on card since HA Core update to 2022.11.1

### ISSUE THREAD

**Issue by SdeGeata** [lukevink/hass-config-lajv#25]
So I, as I'm sure many of you have updated to HA Core 2022.11.1. As soon as I did so, I noticed a "flicker" on my floor-plan card. I was told by someone after I reported it as a bug, that is has to do with the Config-Template-Card refreshing as entity states are changed - only I hadn't changed and entity states. It was a flicker that just went every couple of seconds no matter what was going on. It only manifested after the core update. Please see attached video capture to see the effect.

Has anyone else noticed this? if so, what is the remedy?

My temporary fix was to downgrade the Core to 2022.10.5, so it is at least usable and doesn't manifest the undesired effect. I admit though, this is a temporary fix.

Any input is appreciated.

https://user-images.githubusercontent.com/5808871/200188813-846a8a93-22fa-49f1-b88e-58edca5e5598.mov

**Comment by detroitgoose** [comment]
@SdeGeata Yes same issue.

As noted here [https://github.com/iantrich/config-template-card/issues/114](https://github.com/iantrich/config-template-card/issues/114), the issue appears to be that we've wrapped the entire picture-element card inside of the config-template-card.

This basically means a rewrite of the yaml to put each element into it's own config-template-card. I've yet to do this, and so can't  say how it will all work.

The code below is an example of a "properly configured" elements card, as suggested by the author of the [config-template-card](https://github.com/iantrich/config-template-card):

```
type: picture-elements
image: http://hs.sbcounty.gov/CN/Photo%20Gallery/_t/Sample%20Picture%20-%20Koala_jpg.jpg?Mobile=0
elements:
  - type: 'custom:config-template-card'
    variables:
      - states['light.bed_light'].state
    entities:
      - light.bed_light
      - sensor.light_icon_color
    element:
      type: icon
      icon: "${vars[0] === 'on' ? 'mdi:home' : 'mdi:circle'}"
      style:
        '--paper-item-icon-color': '${ states[''sensor.light_icon_color''].state }'
    style:
      top: 47%
      left: 75%
```

Yes. I expect this to be a big headache to rewrite...
